/* 
 * Knetik Platform API Documentation Latest
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GamificationLeaderboardsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class GamificationLeaderboardsApiTests
    {
        private GamificationLeaderboardsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new GamificationLeaderboardsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GamificationLeaderboardsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' GamificationLeaderboardsApi
            //Assert.IsInstanceOfType(typeof(GamificationLeaderboardsApi), instance, "instance is a GamificationLeaderboardsApi");
        }

        
        /// <summary>
        /// Test GetLeaderboardUsingGET
        /// </summary>
        [Test]
        public void GetLeaderboardUsingGETTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string contextType = null;
            //string contextId = null;
            //int? size = null;
            //int? page = null;
            //var response = instance.GetLeaderboardUsingGET(contextType, contextId, size, page);
            //Assert.IsInstanceOf<LeaderboardResource> (response, "response is LeaderboardResource");
        }
        
        /// <summary>
        /// Test GetStrategiesUsingGET
        /// </summary>
        [Test]
        public void GetStrategiesUsingGETTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetStrategiesUsingGET();
            //Assert.IsInstanceOf<List<string>> (response, "response is List<string>");
        }
        
        /// <summary>
        /// Test GetUserRankUsingGET
        /// </summary>
        [Test]
        public void GetUserRankUsingGETTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string contextType = null;
            //string contextId = null;
            //string id = null;
            //var response = instance.GetUserRankUsingGET(contextType, contextId, id);
            //Assert.IsInstanceOf<LeaderboardEntryResource> (response, "response is LeaderboardEntryResource");
        }
        
    }

}
