/* 
 * Knetik Platform API Documentation Latest
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PaymentsGoogleApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class PaymentsGoogleApiTests
    {
        private PaymentsGoogleApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PaymentsGoogleApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PaymentsGoogleApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' PaymentsGoogleApi
            //Assert.IsInstanceOfType(typeof(PaymentsGoogleApi), instance, "instance is a PaymentsGoogleApi");
        }

        
        /// <summary>
        /// Test HandlePaymentUsingPOST
        /// </summary>
        [Test]
        public void HandlePaymentUsingPOSTTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GooglePaymentRequest request = null;
            //var response = instance.HandlePaymentUsingPOST(request);
            //Assert.IsInstanceOf<int?> (response, "response is int?");
        }
        
    }

}
