/* 
 * Knetik Platform API Documentation latest 
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PaymentsPayPalClassicApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class PaymentsPayPalClassicApiTests
    {
        private PaymentsPayPalClassicApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PaymentsPayPalClassicApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PaymentsPayPalClassicApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' PaymentsPayPalClassicApi
            //Assert.IsInstanceOfType(typeof(PaymentsPayPalClassicApi), instance, "instance is a PaymentsPayPalClassicApi");
        }

        
        /// <summary>
        /// Test CreateBillingAgreementUrlUsingPOST
        /// </summary>
        [Test]
        public void CreateBillingAgreementUrlUsingPOSTTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateBillingAgreementRequest request = null;
            //var response = instance.CreateBillingAgreementUrlUsingPOST(request);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test ExpressCheckoutUsingPOST
        /// </summary>
        [Test]
        public void ExpressCheckoutUsingPOSTTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreatePayPalPaymentRequest request = null;
            //var response = instance.ExpressCheckoutUsingPOST(request);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test FinalizeBillingAgreementUsingPOST
        /// </summary>
        [Test]
        public void FinalizeBillingAgreementUsingPOSTTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //FinalizeBillingAgreementRequest request = null;
            //var response = instance.FinalizeBillingAgreementUsingPOST(request);
            //Assert.IsInstanceOf<int?> (response, "response is int?");
        }
        
        /// <summary>
        /// Test FinalizeCheckoutUsingPOST
        /// </summary>
        [Test]
        public void FinalizeCheckoutUsingPOSTTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //FinalizePayPalPaymentRequest request = null;
            //instance.FinalizeCheckoutUsingPOST(request);
            
        }
        
    }

}
