/* 
 * Knetik Platform API Documentation Latest
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PaymentsStripeApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class PaymentsStripeApiTests
    {
        private PaymentsStripeApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PaymentsStripeApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PaymentsStripeApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' PaymentsStripeApi
            //Assert.IsInstanceOfType(typeof(PaymentsStripeApi), instance, "instance is a PaymentsStripeApi");
        }

        
        /// <summary>
        /// Test CreateCustomerUsingPOST1
        /// </summary>
        [Test]
        public void CreateCustomerUsingPOST1Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //StripeCreatePaymentMethod request = null;
            //var response = instance.CreateCustomerUsingPOST1(request);
            //Assert.IsInstanceOf<PaymentMethodResource> (response, "response is PaymentMethodResource");
        }
        
        /// <summary>
        /// Test PayInvoiceUsingPOST1
        /// </summary>
        [Test]
        public void PayInvoiceUsingPOST1Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //StripePaymentRequest request = null;
            //instance.PayInvoiceUsingPOST1(request);
            
        }
        
    }

}
