/* 
 * Knetik Platform API Documentation latest 
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UsersAddressesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class UsersAddressesApiTests
    {
        private UsersAddressesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new UsersAddressesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UsersAddressesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' UsersAddressesApi
            //Assert.IsInstanceOfType(typeof(UsersAddressesApi), instance, "instance is a UsersAddressesApi");
        }

        
        /// <summary>
        /// Test CreateAddressUsingPOST
        /// </summary>
        [Test]
        public void CreateAddressUsingPOSTTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userId = null;
            //SavedAddressResource savedAddressResource = null;
            //var response = instance.CreateAddressUsingPOST(userId, savedAddressResource);
            //Assert.IsInstanceOf<SavedAddressResource> (response, "response is SavedAddressResource");
        }
        
        /// <summary>
        /// Test DeleteAddressUsingDELETE
        /// </summary>
        [Test]
        public void DeleteAddressUsingDELETETest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userId = null;
            //int? id = null;
            //instance.DeleteAddressUsingDELETE(userId, id);
            
        }
        
        /// <summary>
        /// Test GetAddressUsingGET
        /// </summary>
        [Test]
        public void GetAddressUsingGETTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userId = null;
            //int? id = null;
            //var response = instance.GetAddressUsingGET(userId, id);
            //Assert.IsInstanceOf<SavedAddressResource> (response, "response is SavedAddressResource");
        }
        
        /// <summary>
        /// Test GetAddressesUsingGET
        /// </summary>
        [Test]
        public void GetAddressesUsingGETTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userId = null;
            //int? size = null;
            //int? page = null;
            //string order = null;
            //var response = instance.GetAddressesUsingGET(userId, size, page, order);
            //Assert.IsInstanceOf<PageResourceSavedAddressResource> (response, "response is PageResourceSavedAddressResource");
        }
        
        /// <summary>
        /// Test UpdateAddressUsingPUT
        /// </summary>
        [Test]
        public void UpdateAddressUsingPUTTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userId = null;
            //int? id = null;
            //SavedAddressResource savedAddressResource = null;
            //instance.UpdateAddressUsingPUT(userId, id, savedAddressResource);
            
        }
        
    }

}
