/* 
 * Knetik Platform API Documentation Latest
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CustomerConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CustomerConfigTests
    {
        // TODO uncomment below to declare an instance variable for CustomerConfig
        //private CustomerConfig instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CustomerConfig
            //instance = new CustomerConfig();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CustomerConfig
        /// </summary>
        [Test]
        public void CustomerConfigInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CustomerConfig
            //Assert.IsInstanceOfType<CustomerConfig> (instance, "variable 'instance' is a CustomerConfig");
        }

        /// <summary>
        /// Test the property 'Aliases'
        /// </summary>
        [Test]
        public void AliasesTest()
        {
            // TODO unit test for the property 'Aliases'
        }
        /// <summary>
        /// Test the property 'Database'
        /// </summary>
        [Test]
        public void DatabaseTest()
        {
            // TODO unit test for the property 'Database'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'UploadBucket'
        /// </summary>
        [Test]
        public void UploadBucketTest()
        {
            // TODO unit test for the property 'UploadBucket'
        }

    }

}
