/* 
 * Knetik Platform API Documentation Latest
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DatabaseConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DatabaseConfigTests
    {
        // TODO uncomment below to declare an instance variable for DatabaseConfig
        //private DatabaseConfig instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DatabaseConfig
            //instance = new DatabaseConfig();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DatabaseConfig
        /// </summary>
        [Test]
        public void DatabaseConfigInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DatabaseConfig
            //Assert.IsInstanceOfType<DatabaseConfig> (instance, "variable 'instance' is a DatabaseConfig");
        }

        /// <summary>
        /// Test the property 'Mongo'
        /// </summary>
        [Test]
        public void MongoTest()
        {
            // TODO unit test for the property 'Mongo'
        }
        /// <summary>
        /// Test the property 'Sql'
        /// </summary>
        [Test]
        public void SqlTest()
        {
            // TODO unit test for the property 'Sql'
        }

    }

}
